<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>state_personal_data</name>
   <tag></tag>
   <elementGuidId>d85bd906-17e5-44d0-b978-b38b6f9819a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div/section[2]/div/div/div[1]/div[1]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.position-absolute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6bad68fa-5e6b-4648-8c6a-708e53a21404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>position-absolute</value>
      <webElementGuid>fbd5b9ff-4325-4c6b-a9e9-3b8d324c63da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icon/check-done.svg</value>
      <webElementGuid>9ff04ef4-67fd-434c-a913-938eb2bd4700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>base-circle</value>
      <webElementGuid>b081c014-6ed4-4267-871d-320405721df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;progress-bar&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;flex-nowrap row&quot;]/div[@class=&quot;p-0 text-center width-custom col-auto&quot;]/div[@class=&quot;position-relative base-progress&quot;]/div[@class=&quot;position-relative base-img&quot;]/a[1]/img[@class=&quot;position-absolute&quot;]</value>
      <webElementGuid>c98e9bd4-09e3-417a-93aa-e550cab39a26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[2]/div/div/div/div/div[2]/a/img</value>
      <webElementGuid>dc67164a-88eb-4c30-907b-344701a2fd2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='base-circle']</value>
      <webElementGuid>77d51423-c9bf-4ce0-86f5-c0f784fa15d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/a/img</value>
      <webElementGuid>dfe22ec3-1d73-4580-b6b0-b09420f11852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/icon/check-done.svg' and @alt = 'base-circle']</value>
      <webElementGuid>3fb5b114-71fa-466b-bce4-7a431186c5a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
