<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_DataFiles</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3f682eeb-8e8c-4579-94e8-3aac2d9333e3</testSuiteGuid>
   <testCaseLink>
      <guid>68160419-1c39-40e0-8653-1736e646e358</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/Login akun terverifikasi dengan Data Files</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2cf596d8-a878-4eeb-961d-db8003b72423</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2cf596d8-a878-4eeb-961d-db8003b72423</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>b1ca64a2-d1de-49b2-9f6f-f4242f7751ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2cf596d8-a878-4eeb-961d-db8003b72423</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>14f3bdd4-189e-4d0c-86e4-45f1aa2c4693</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
