<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_tempat_lahir</name>
   <tag></tag>
   <elementGuidId>687ae744-0ac5-4263-b2b6-487874c11566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Tempat Tanggal Lahir *' or . = 'Tempat Tanggal Lahir *')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3ff7c274-11ee-4287-ac54-a5fbf27cb347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>tempat_lahir</value>
      <webElementGuid>e2326932-1354-4ed9-a70a-0de5d2fc6932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label cl-black</value>
      <webElementGuid>8b72c1c7-5c7e-4cde-a845-faaa2a62b76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tempat Tanggal Lahir *</value>
      <webElementGuid>217ec8ed-d91e-4de9-8b22-77f7c82fb219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section&quot;]/form[@class=&quot;form color-custom&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-12&quot;]/div[@class=&quot;form-group pe-30&quot;]/label[@class=&quot;form-label cl-black&quot;]</value>
      <webElementGuid>3c66ea7a-3e97-49a1-a096-2c32ef85ac49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[5]/div/div/label</value>
      <webElementGuid>4cd59b5c-b84a-4266-97b2-a1a487401b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih...'])[2]/following::label[1]</value>
      <webElementGuid>a5ee95c8-11d5-473d-9595-496b92f1f7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::label[1]</value>
      <webElementGuid>6f65d4ad-f200-4ac5-9464-0702a8853fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tempat Tanggal Lahir']/parent::*</value>
      <webElementGuid>52860103-387f-4c3c-af1d-59efbf1ae829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/label</value>
      <webElementGuid>0c99f804-f5fc-4c76-ba3b-b6ea33b0c4c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Tempat Tanggal Lahir *' or . = 'Tempat Tanggal Lahir *')]</value>
      <webElementGuid>617d9a42-e184-4e1c-848d-bc882f754943</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
