<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_pertanyaan4_tidak</name>
   <tag></tag>
   <elementGuidId>f17564d0-928c-44e7-89da-cb9100134180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[3]/form/div[4]/div[2]/div/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ket_lain_4_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>237c6be5-770c-4387-8334-96ce415736f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>2f32be6a-457f-419d-8ae9-8fa565663856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f58caafa-13a7-4406-a7a0-88f38c7551ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ket_lain_4</value>
      <webElementGuid>08636403-fca0-4dd2-996a-c6d6418e1a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ket_lain_4_2</value>
      <webElementGuid>ac1fdf82-0fcc-4325-88c5-7af4d17af96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ket_lain_4_2&quot;)</value>
      <webElementGuid>e51c3847-d448-4bf3-99ac-2523a2645106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ket_lain_4_2']</value>
      <webElementGuid>d35ec1f5-91fd-4aac-bc5b-10a9b0a5af97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[4]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>59f5359a-22f6-4c3b-b76c-b8894c583a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div[2]/input</value>
      <webElementGuid>dc4fd0dc-2875-4b71-9e4b-83fa02cb7cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ket_lain_4' and @id = 'ket_lain_4_2']</value>
      <webElementGuid>d2b771e3-938e-4469-85c5-ea37d375e788</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
