<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_lihat_detail_pekerjaan</name>
   <tag></tag>
   <elementGuidId>757acbd4-8ad5-4c01-a68a-7ba1c50e0aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-collapse.btn.btn-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dbcb6dae-df60-4b15-8419-bca898e4cc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1faec380-e920-46ca-a723-5ec92f93ec92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>example-collapse-text-0</value>
      <webElementGuid>23748521-90fc-46db-8686-1b22fbe3c8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-collapse btn btn-link</value>
      <webElementGuid>d2f113f2-23e4-45cd-a2a5-88110d5fcd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Detail Pekerjaan</value>
      <webElementGuid>88bf9186-1d55-4636-b5c9-f81f0a12ef61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)/div[@class=&quot;list-card&quot;]/div[@class=&quot;justify-content-center row&quot;]/div[@class=&quot;application-card col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;d-flex align-items-end col-sm-8 col-6&quot;]/button[@class=&quot;button-collapse btn btn-link&quot;]</value>
      <webElementGuid>2796ae20-1f9a-4c55-9b2f-a3b3f36d7cba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>da4d7898-3926-44af-9736-67abf3655a9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='list']/div/div/div/div[3]/div/button</value>
      <webElementGuid>fc9f57b4-a49a-4ce4-ab73-eac0a4434a8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bandung'])[2]/following::button[1]</value>
      <webElementGuid>143c1948-16f2-4aef-bfde-17dcdcfd469d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Magang Bisnis Indonesia'])[2]/preceding::button[1]</value>
      <webElementGuid>1d7e9579-2d56-4f0e-b40d-1fae626bc3db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deskripsi Pekerjaan:'])[1]/preceding::button[1]</value>
      <webElementGuid>01b9ed89-082c-4bb9-88cc-089f3cc0e616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Detail Pekerjaan']/parent::*</value>
      <webElementGuid>c984cc5f-3dd9-46b4-a59d-a998de846d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>0e1dfcf4-22b6-4bea-bc77-cef621cb8eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Lihat Detail Pekerjaan' or . = 'Lihat Detail Pekerjaan')]</value>
      <webElementGuid>a472aacf-e105-4be4-89d8-b36bb1a9c98c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
