<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_pendidikan_suami_istri</name>
   <tag></tag>
   <elementGuidId>cdcd16c9-9c80-4924-b657-ca3c8362e3c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='pendidikan0'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a34e07db-0aca-42f0-983b-b6d1a9cada85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>cdb39e55-f35b-4253-bd94-642847120a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pendidikan0</value>
      <webElementGuid>c9321346-7c3e-40ae-a5f1-49e31fca04c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih...Tidak / Belum SekolahSDSMPSMAD1D2D3D4S1S2S3</value>
      <webElementGuid>7dfff131-e167-4893-8371-a4ae9676fae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;undefined&quot;]/td[@class=&quot;py-3&quot;]/select[@id=&quot;pendidikan0&quot;]</value>
      <webElementGuid>b900a724-9b03-4a0a-907f-d3a6014ab361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='pendidikan0'])[3]</value>
      <webElementGuid>cce3bdac-9913-4fc2-bc92-6b5e00d48f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[4]/table/tbody/tr/td[5]/select</value>
      <webElementGuid>e20e691d-0d8c-414b-8fcf-6861c949722b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suami / Istri'])[1]/following::select[2]</value>
      <webElementGuid>7ba4ec0e-c043-44c5-afc1-8c0764432bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Telepon'])[1]/following::select[2]</value>
      <webElementGuid>004fef4d-1a19-441b-978c-40e167326f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak Ke- 1'])[1]/preceding::select[1]</value>
      <webElementGuid>b0aa6127-d4a0-4182-921d-bc311b9354be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak Ke- 2'])[1]/preceding::select[3]</value>
      <webElementGuid>37913c65-3fd1-4ff8-b62f-abe758f08338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[5]/select</value>
      <webElementGuid>5db0b260-3a63-41d6-8673-217e8a1bbe2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pendidikan0' and (text() = 'Pilih...Tidak / Belum SekolahSDSMPSMAD1D2D3D4S1S2S3' or . = 'Pilih...Tidak / Belum SekolahSDSMPSMAD1D2D3D4S1S2S3')]</value>
      <webElementGuid>46e1c0a5-be1f-4b2c-a68c-ef83b14bf076</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
