<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pekerjaan_anak1_section2</name>
   <tag></tag>
   <elementGuidId>a79d4155-77bb-41c3-84a6-cc8a43f9ef6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.null > td.py-3 > #pekerjaan0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='pekerjaan1'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dda2bac2-cc76-42c6-83e3-535bfb7df20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f8b5c81a-11f4-4bb2-91d4-498b2a9b9f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e13f400d-cf74-4d55-bcb7-cd26a0edfb81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>67565403-ff0b-48e5-b405-1af9aeff7f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pekerjaan0</value>
      <webElementGuid>2b19f07d-f6fa-4ad7-8e69-7ce9b3eae01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;null&quot;]/td[@class=&quot;py-3&quot;]/input[@id=&quot;pekerjaan0&quot;]</value>
      <webElementGuid>c11e6558-9158-4059-aa35-c78b57c65bed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='pekerjaan0'])[3]</value>
      <webElementGuid>54a66073-8edf-47f4-8abd-dc87b3e7dbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[4]/table/tbody/tr/td[6]/input</value>
      <webElementGuid>db118b43-bf8c-46c3-a325-232c184b1ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[6]/input</value>
      <webElementGuid>a04561b5-d4d2-4495-849e-399407af9332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pekerjaan0']</value>
      <webElementGuid>14f94dc1-ba48-4f26-96b2-e199eb5e7e02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
