<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_pekerjaan_anak2</name>
   <tag></tag>
   <elementGuidId>ad7f5abc-1e72-4177-bd65-448cd0a796e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pekerjaan0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pekerjaan3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef11b46b-d859-4760-a958-42f9f6855d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb5a81ee-d7ce-4421-8d7f-4e1c4b5cc057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>11e8ef32-5e7e-440d-8d45-8b0a1e6a3689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8e3a833a-dc24-44ba-9902-82991002a07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pekerjaan0</value>
      <webElementGuid>a88b84b8-13fa-4370-988f-6770848d0bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>92fcbe51-d0e4-4ab9-b741-3e7eac65dbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;undefined&quot;]/td[@class=&quot;py-3&quot;]/input[@id=&quot;pekerjaan0&quot;]</value>
      <webElementGuid>64ad013b-053b-4ed7-a049-a396e3ecd29d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pekerjaan0']</value>
      <webElementGuid>9ccbe339-148d-499d-a8c0-edf9a4c2a039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div/table/tbody/tr/td[6]/input</value>
      <webElementGuid>a839d974-f0f9-4a78-aa35-665f6a91e964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>6ce4df16-bed3-42f8-ae8f-a45ddfb37f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pekerjaan0']</value>
      <webElementGuid>f944adaf-222d-40ef-8c3e-692b24fe4182</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
