<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_dropdown_jenis_kelamin_anak1</name>
   <tag></tag>
   <elementGuidId>a372f3ff-76b3-475c-a830-763dfd4c3b8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jenis_kelamin2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jenis_kelamin2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b7198a74-ccfd-4e6c-9c1a-d0174a86d33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>3a007ebc-2f64-4f7a-bf59-40c48c884aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenis_kelamin2</value>
      <webElementGuid>d65a28dd-87a0-4257-8686-667d8af61427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih...LP</value>
      <webElementGuid>7361d131-0507-451b-81a3-094355b06cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;undefined&quot;]/td[@class=&quot;py-3&quot;]/select[@id=&quot;jenis_kelamin2&quot;]</value>
      <webElementGuid>a185ed0f-57fd-4d12-96b2-3c0d1183ea8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jenis_kelamin2']</value>
      <webElementGuid>05d490e9-c739-4048-aaf8-37555aa1026b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div/table/tbody/tr[3]/td[3]/select</value>
      <webElementGuid>d6f3d512-61fb-4c12-9604-c2e206401176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak 1'])[1]/following::select[1]</value>
      <webElementGuid>349cde65-578e-4b6f-97ae-2451283046f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[3]</value>
      <webElementGuid>3d0950b0-6084-444d-8e10-6456af8284ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak 2'])[1]/preceding::select[2]</value>
      <webElementGuid>89accb6b-dfec-4df8-b759-04cc4925603f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak 3'])[1]/preceding::select[4]</value>
      <webElementGuid>b7e7db0c-ba84-4085-8e93-e3fe563c1067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/select</value>
      <webElementGuid>012751ec-92e9-4662-8592-02108724a8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'jenis_kelamin2' and (text() = 'Pilih...LP' or . = 'Pilih...LP')]</value>
      <webElementGuid>cf7bc3fe-3a7a-4e1d-8e80-b75b7dee6ef6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
