<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_dropdown_jenis_kelamin_anak1_section2</name>
   <tag></tag>
   <elementGuidId>e92c8a09-ef6b-44ec-9b2b-483b4b56012d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr.null > td.py-3 > #jenis_kelamin0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@id='jenis_kelamin1'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>df2c8024-ffdd-446e-9845-555c10e49d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>20e5bca4-57d8-4fbc-bf48-e2ea9efcd5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenis_kelamin0</value>
      <webElementGuid>e15d10c9-2b59-4f62-bdfd-3e87f2452c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih...LP</value>
      <webElementGuid>59e53cee-1bf5-42a0-a820-34bb2775f045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;null&quot;]/td[@class=&quot;py-3&quot;]/select[@id=&quot;jenis_kelamin0&quot;]</value>
      <webElementGuid>46e7ff83-7f79-4c80-a5e2-7a3ebbc61a05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@id='jenis_kelamin0'])[3]</value>
      <webElementGuid>7fa01068-5db2-4669-8d60-67416a4be9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[4]/table/tbody/tr/td[3]/select</value>
      <webElementGuid>34f355c7-bf05-421e-9b34-83f92e208fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suami / Istri'])[1]/following::select[1]</value>
      <webElementGuid>898c1b36-22f0-4830-9188-74f38bee0d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Telepon'])[1]/following::select[1]</value>
      <webElementGuid>0fd1ed51-55ee-43bb-b3c8-89d74a17bcdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak Ke- 1'])[1]/preceding::select[2]</value>
      <webElementGuid>5e811104-ecd6-49e9-b658-e20c4eac9d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak Ke- 2'])[1]/preceding::select[4]</value>
      <webElementGuid>5526cdc7-d943-48af-9d39-bfb421ded13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[3]/select</value>
      <webElementGuid>67121475-370a-4100-8b2a-86e0931aa1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'jenis_kelamin0' and (text() = 'Pilih...LP' or . = 'Pilih...LP')]</value>
      <webElementGuid>e9b8223b-dfca-46b0-9dab-421809506c47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
