<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_dropdown_pendidikan_ibu</name>
   <tag></tag>
   <elementGuidId>5ef80b0b-e15d-4169-b11b-87802a0b8b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pendidikan0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pendidikan1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>375c9865-d916-48cb-a01c-a023e67ecdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>8e6b9c1f-a6dd-4af9-a688-40d8b2a31642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pendidikan0</value>
      <webElementGuid>185e9e22-9a08-4de3-99b7-a12fa564774f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih...Tidak / Belum SekolahSDSMPSMAD1D2D3D4S1S2S3</value>
      <webElementGuid>f8e02991-2829-4653-ae86-1c369efbaccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;null&quot;]/td[@class=&quot;py-3&quot;]/select[@id=&quot;pendidikan0&quot;]</value>
      <webElementGuid>fb079576-9e19-49e4-8cce-74bfd7bf7d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pendidikan0']</value>
      <webElementGuid>2683a70a-2d38-434f-b730-6ac7a6cc5d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div/table/tbody/tr/td[5]/select</value>
      <webElementGuid>c64aaa6e-7edf-4e66-8b7a-99b232f34efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[2]</value>
      <webElementGuid>47195493-a139-48ab-8d90-29d548c09bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>7db57435-a9d1-45ac-95fb-d5eeea20d72f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/select</value>
      <webElementGuid>fa85c890-f3b4-4968-bb28-85223ac3c513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pendidikan0' and (text() = 'Pilih...Tidak / Belum SekolahSDSMPSMAD1D2D3D4S1S2S3' or . = 'Pilih...Tidak / Belum SekolahSDSMPSMAD1D2D3D4S1S2S3')]</value>
      <webElementGuid>ee1f56f5-9da0-4d32-b756-e288c1086307</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
