<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_dropdown_pendidikan_anak1</name>
   <tag></tag>
   <elementGuidId>2c73a602-d53f-4894-9357-c2c608d842f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pendidikan0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pendidikan2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8a1687c7-64b5-467d-8ed5-d99d797f4d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>22c4dc06-82d6-4ff1-8027-2ba4ce5c3197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pendidikan0</value>
      <webElementGuid>f5b5ea53-7a16-4f03-8c78-15ffa7e463ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih...Tidak / Belum SekolahSDSMPSMAD1D2D3D4S1S2S3</value>
      <webElementGuid>eef21e34-f63c-4573-b09e-5d33310682f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;null&quot;]/td[@class=&quot;py-3&quot;]/select[@id=&quot;pendidikan0&quot;]</value>
      <webElementGuid>b2234e3d-6bf4-412d-9009-20a2c74d8af5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pendidikan0']</value>
      <webElementGuid>d452e0d9-9754-431c-8c96-7548f72fbcba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div/table/tbody/tr/td[5]/select</value>
      <webElementGuid>adcc55d3-632e-4ba0-8ab7-fff1e53c809d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[2]</value>
      <webElementGuid>445a11a9-cb9f-4ec2-82b6-be2f337a8700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>ac44c9ca-3256-4297-961a-e6a9791e255e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/select</value>
      <webElementGuid>7eb837b6-a3a5-414d-99e4-04050068e3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pendidikan0' and (text() = 'Pilih...Tidak / Belum SekolahSDSMPSMAD1D2D3D4S1S2S3' or . = 'Pilih...Tidak / Belum SekolahSDSMPSMAD1D2D3D4S1S2S3')]</value>
      <webElementGuid>fffca293-4ca5-495f-9abd-8f07135ef7ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
