<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_dropdown_jenis_kelamin_anak2</name>
   <tag></tag>
   <elementGuidId>162655e7-47c3-46a6-b8a3-51b10c7b7255</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jenis_kelamin2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='jenis_kelamin3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bfaf5778-7d1e-4e2a-a278-19b1c74de97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>a0a9364b-1f98-4dca-ba61-8a4395658f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jenis_kelamin2</value>
      <webElementGuid>16cb1eee-dc17-403d-aa31-b436c541bebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih...LP</value>
      <webElementGuid>c4382acf-327a-423c-8633-2edfe4c9c2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;undefined&quot;]/td[@class=&quot;py-3&quot;]/select[@id=&quot;jenis_kelamin2&quot;]</value>
      <webElementGuid>7dc988c6-c03a-40ef-80a4-978aee4f1e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jenis_kelamin2']</value>
      <webElementGuid>03e02ff7-6a15-4fa0-be59-3643e2c1ede2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div/table/tbody/tr[3]/td[3]/select</value>
      <webElementGuid>b4c034c2-1fb6-477e-b292-eaa2a747bfc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak 1'])[1]/following::select[1]</value>
      <webElementGuid>a6ecd160-de52-4b61-82ea-6a70c02d22f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[3]</value>
      <webElementGuid>a480dc92-d424-427f-a31b-e7dd48a0b6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak 2'])[1]/preceding::select[2]</value>
      <webElementGuid>c53cb578-cc45-4c24-87bb-263975acb1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anak 3'])[1]/preceding::select[4]</value>
      <webElementGuid>57433a53-5701-4fc9-aa78-e5cdfe48e6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/select</value>
      <webElementGuid>9eb9d43b-1e23-4ba4-a97b-9c084ad57697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'jenis_kelamin2' and (text() = 'Pilih...LP' or . = 'Pilih...LP')]</value>
      <webElementGuid>f90af5f7-de4b-4cb0-8c93-23e9302d8b88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
