<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_edit_pengalaman3</name>
   <tag></tag>
   <elementGuidId>6afdc0ed-7c00-4913-a0bf-92a2cef36c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[3]/form/div[5]/div[3]/div/button[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>81678cbd-cd7c-49cd-903a-2fc7695f843a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>447a09a9-881f-4a9b-a402-649e00e2a43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-edit</value>
      <webElementGuid>7619cb81-f946-4f48-acf9-69103bd74ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icon/icon-edit.svg</value>
      <webElementGuid>38a62d34-6208-4118-91ed-791d41df2206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section&quot;]/form[@class=&quot;form color-custom&quot;]/div[@class=&quot;list-experience mb-4 row&quot;]/div[@class=&quot;d-flex justify-content-end align-items-start col-sm-2 col-2&quot;]/div[@class=&quot;mobile-dis-none&quot;]/button[@class=&quot;p-0&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>1828927a-409e-497e-8593-a6e8741915a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[5]/div[3]/div/button[2]/img</value>
      <webElementGuid>5d6c1b41-3214-43a8-9faa-2c69baab6804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon-edit'])[6]</value>
      <webElementGuid>7b11b455-f9e1-447f-bb02-f598c41a57b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/button[2]/img</value>
      <webElementGuid>885654cd-c323-4f63-b0e9-e84cb7af5b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon-edit' and @src = '/icon/icon-edit.svg']</value>
      <webElementGuid>97db5d35-6a7f-4d4d-a054-bcd3e589c0d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
