<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_hapus_pengalaman2</name>
   <tag></tag>
   <elementGuidId>bd17a61e-0b20-4f5e-a8b6-8eb69e835d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[3]/form/div[4]/div[3]/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f0ff3407-ab2a-4d69-8c32-054f5c43d4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>dc072fcc-6b0e-4734-891d-16579bbe49f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-delete</value>
      <webElementGuid>d7c239e5-7545-4815-ace1-d945cfb6288b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icon/icon-delete.svg</value>
      <webElementGuid>87cd306a-2e43-499a-95af-0cf9106530c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section&quot;]/form[@class=&quot;form color-custom&quot;]/div[@class=&quot;list-experience mb-4 row&quot;]/div[@class=&quot;d-flex justify-content-end align-items-start col-sm-2 col-2&quot;]/div[@class=&quot;mobile-dis-none&quot;]/button[@class=&quot;p-0 me-3&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>03f24cb7-e3c5-4af8-88c8-7aff3dc312fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[4]/div[3]/div/button/img</value>
      <webElementGuid>4d975b92-a7e5-4d76-817c-3949b77b4ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon-delete'])[4]</value>
      <webElementGuid>40557eee-4e8c-48f3-93ad-abe1023d9cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/button/img</value>
      <webElementGuid>eb946024-0431-4e5f-b96c-2ba9ac5d1e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon-delete' and @src = '/icon/icon-delete.svg']</value>
      <webElementGuid>dd6ab407-9f77-4ed4-a550-632e624de5cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
