<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_add_pengalaman</name>
   <tag></tag>
   <elementGuidId>01a7e973-f527-4c20-8d6c-68b77873fbc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[3]/form/div/div[2]/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon-add.me-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1594fa4f-7c5f-4a67-89c2-cfad4303c964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-add me-2</value>
      <webElementGuid>8c7fb89f-72d4-447c-9ae3-30f6060b0945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-plus</value>
      <webElementGuid>9d3ceba5-1b44-4b5a-9ca2-263702a63797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icon/icon-plus.svg</value>
      <webElementGuid>ba2a1118-094b-49cb-9c6c-f130989d60b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section&quot;]/form[@class=&quot;form color-custom&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;d-flex align-items-end justify-content-end col-sm-4 col-12&quot;]/div[@class=&quot;form-group false&quot;]/button[@class=&quot;p-0&quot;]/img[@class=&quot;icon-add me-2&quot;]</value>
      <webElementGuid>ce9ed904-fbf6-4f5a-80d7-d3b762a9bda9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div/div[2]/div/button/img</value>
      <webElementGuid>61e19b76-cc2b-4ba9-9dbe-4d7e29097d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon-plus']</value>
      <webElementGuid>dc757f68-7421-4aeb-97c6-15a934dfa42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/img</value>
      <webElementGuid>dac53f60-b70b-42c4-acae-f4d7a5fa63c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon-plus' and @src = '/icon/icon-plus.svg']</value>
      <webElementGuid>0a770550-689c-4930-a87a-389c80091a00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
