<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_edit_pengalaman2</name>
   <tag></tag>
   <elementGuidId>82d3faf2-88b5-48a4-aa1d-27a574c7ecd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[3]/form/div[4]/div[3]/div/button[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>aa258336-c5f2-4bca-b9a9-085ca90c60b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>8c42c374-9514-4d18-ab40-885a28d5ca10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-edit</value>
      <webElementGuid>1a46549a-b37c-4926-be4e-5c94b1e21474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icon/icon-edit.svg</value>
      <webElementGuid>681fb3e6-4dd0-4a67-982d-9be96865a362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section&quot;]/form[@class=&quot;form color-custom&quot;]/div[@class=&quot;list-experience mb-4 row&quot;]/div[@class=&quot;d-flex justify-content-end align-items-start col-sm-2 col-2&quot;]/div[@class=&quot;mobile-dis-none&quot;]/button[@class=&quot;p-0&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>326b7cd8-785c-44a5-ae41-e935176fdf59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[4]/div[3]/div/button[2]/img</value>
      <webElementGuid>1150aadd-28a5-4b9e-aafc-956a96dd3acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon-edit'])[4]</value>
      <webElementGuid>c057901a-6741-4c38-8ba7-c4be45e58195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/button[2]/img</value>
      <webElementGuid>ab564b74-b654-4ac6-a7e5-d1890b5453da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon-edit' and @src = '/icon/icon-edit.svg']</value>
      <webElementGuid>9291a13c-d7a8-4ff0-a9e1-f76112ae30f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
