<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_hapus_pengalaman3</name>
   <tag></tag>
   <elementGuidId>9816b564-122c-40a7-8957-595c248dbe51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[3]/form/div[5]/div[3]/div/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3aec562d-a8e1-4ad1-9b9f-f5885d4055ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>4b822cd9-5c05-42f0-a2a7-21fab0caf72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-delete</value>
      <webElementGuid>a4f49c67-70f6-48f5-ab17-a550c62388c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icon/icon-delete.svg</value>
      <webElementGuid>4cd5db15-5c6e-4171-9950-648c2834430d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section&quot;]/form[@class=&quot;form color-custom&quot;]/div[@class=&quot;list-experience mb-4 row&quot;]/div[@class=&quot;d-flex justify-content-end align-items-start col-sm-2 col-2&quot;]/div[@class=&quot;mobile-dis-none&quot;]/button[@class=&quot;p-0 me-3&quot;]/img[@class=&quot;icon&quot;]</value>
      <webElementGuid>01cf4a18-8621-47f6-b04e-263377a34e0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[5]/div[3]/div/button/img</value>
      <webElementGuid>cdaf5614-955e-4307-8290-465b8ed4175d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon-delete'])[6]</value>
      <webElementGuid>e7055757-3a77-4f71-a5c4-1538a28fc976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/button/img</value>
      <webElementGuid>024ce384-ba37-4373-a652-fbb539de6106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon-delete' and @src = '/icon/icon-delete.svg']</value>
      <webElementGuid>8a854da3-dd23-44df-b6ac-cb7919a48acc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
