<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_add_pengalaman_bottom2</name>
   <tag></tag>
   <elementGuidId>052b10fa-0496-4bae-8522-40bb5e73f210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[3]/form/div[4]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon-add.mx-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4cc16ef0-46f3-4086-81b8-c69f8c683705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-add mx-2</value>
      <webElementGuid>96e2c004-d96d-4b63-8170-7e711ac47ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-plus</value>
      <webElementGuid>fa793eb4-efd7-4b0b-acfb-df6a19c461fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icon/icon-plus.svg</value>
      <webElementGuid>4b8c7da6-7d2b-4feb-8066-83c700bc48a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section&quot;]/form[@class=&quot;form color-custom&quot;]/div[@class=&quot;form-group text-center mar-cus&quot;]/img[@class=&quot;icon-add mx-2&quot;]</value>
      <webElementGuid>06d85615-7e91-45d9-8cbd-148e5c0858ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[4]/img</value>
      <webElementGuid>9dd5ead6-39b0-4ce0-bc27-48ac6031e30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon-plus']</value>
      <webElementGuid>d6b8d51f-f5a7-4282-9905-540087c529b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/img</value>
      <webElementGuid>844c1b4a-856f-4339-b22d-738862b2fdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon-plus' and @src = '/icon/icon-plus.svg']</value>
      <webElementGuid>f66f5a02-08d2-4d86-aef1-ca2c0a031cce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
