<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_add_pengalaman_bottom1</name>
   <tag></tag>
   <elementGuidId>338ecffe-7aef-4333-a634-628b6884607a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[3]/form/div[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon-add.mx-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>347b9f95-0591-45dd-a302-9e96bf3aeb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-add mx-2</value>
      <webElementGuid>5ce9a8e1-6383-4d0a-baf0-98f020f71bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon-plus</value>
      <webElementGuid>06791bd0-b86b-4815-8d60-8b53b5430814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/icon/icon-plus.svg</value>
      <webElementGuid>85a50944-8392-437e-8408-64f834fef2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section&quot;]/form[@class=&quot;form color-custom&quot;]/div[@class=&quot;form-group text-center mar-cus&quot;]/img[@class=&quot;icon-add mx-2&quot;]</value>
      <webElementGuid>b1ca6577-374b-478d-8a11-1e75104be5c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[3]/img</value>
      <webElementGuid>ba9346d1-339a-44f9-85d6-523477bcc003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon-plus']</value>
      <webElementGuid>61a31094-ea0f-4ccc-8494-90232c38ef30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>983c6c9f-1802-47ef-a98b-74a866a3d8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'icon-plus' and @src = '/icon/icon-plus.svg']</value>
      <webElementGuid>8360c213-6b38-43eb-9840-bf1f77cab450</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
