<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_masih_bekerja_disini2</name>
   <tag></tag>
   <elementGuidId>22f09820-125d-4b90-9cf8-b61aa584d84e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='is_currently'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > div.row > div.col-sm-6.col-12 > div.form-group > div.row > div.d-flex.align-items-center.col-sm-auto.col-auto > div.input-group.d-flex.align-items-center.justify-content-end > div > #is_currently</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5184fe8-1164-491c-b001-f8d3af5d3c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>43870e6a-165a-46fb-9ae4-dc69e29a4e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input me-2</value>
      <webElementGuid>a5ab17d0-cb61-48ea-9790-4e89816947e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_currently</value>
      <webElementGuid>68ca717d-e378-4b85-82b4-6d7be4c214d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_currently</value>
      <webElementGuid>23cb5411-c02c-494e-9130-dfc1f468ccfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>something</value>
      <webElementGuid>07557ec5-aa15-40b4-a7e9-d48d8e043cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section&quot;]/form[@class=&quot;form color-custom&quot;]/div[3]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;d-flex align-items-center  col-sm-auto col-auto&quot;]/div[@class=&quot;input-group d-flex align-items-center justify-content-end&quot;]/div[1]/input[@id=&quot;is_currently&quot;]</value>
      <webElementGuid>59c942d1-3a95-4c8a-8d0c-b5f07cad849e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='is_currently'])[2]</value>
      <webElementGuid>a998bef8-21ab-48d1-bb38-fb832ca0fb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[3]/div[4]/div[2]/div/div/div[4]/div/div/input</value>
      <webElementGuid>f24b7964-f124-43ab-b73e-ce90936e1428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[4]/div[2]/div/div/div[4]/div/div/input</value>
      <webElementGuid>33fb2df8-db40-45c1-a847-dcf8aae8fc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'is_currently' and @name = 'is_currently']</value>
      <webElementGuid>1a380834-c94a-491c-862c-e74653ed693a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
