<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_dropdown_status_karyawan2</name>
   <tag></tag>
   <elementGuidId>8c15066d-f2b2-431c-ba5f-e21059bf1a70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-long-value-select-option-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#react-select-long-value-select-option-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5b1fc71-7b98-45e2-971f-a79232b3f689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-d7l1ni-option</value>
      <webElementGuid>84e10714-a114-43f1-9855-81096d396c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3761ab33-0e34-4f98-af91-6c9d7527bd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-long-value-select-option-1</value>
      <webElementGuid>1a4c37fb-3250-445d-9913-3b7c253deea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>464c3328-d181-40bd-8e15-5ec2d12d4c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tetap</value>
      <webElementGuid>0c0f51d8-ac77-4112-a6a0-e9b78958da08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-long-value-select-option-1&quot;)</value>
      <webElementGuid>22c75c41-c191-48a2-bddb-1251ddc4cc4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-long-value-select-option-1']</value>
      <webElementGuid>969e2bb7-0500-4088-977e-74d8ba2a591f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react-select-long-value-select-listbox']/div/div[2]</value>
      <webElementGuid>19208f29-ad7e-4ab3-bd3b-95f45d55b95d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontrak'])[2]/following::div[1]</value>
      <webElementGuid>3464fb0c-6617-42e1-ae61-59130d07338e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Status Karyawan...'])[1]/following::div[7]</value>
      <webElementGuid>0c2c91df-79ba-4897-a11f-2a10067afbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Magang'])[1]/preceding::div[1]</value>
      <webElementGuid>1d2ec62b-219e-4e8e-a9a9-b021a632f086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Freelance'])[1]/preceding::div[2]</value>
      <webElementGuid>84a2b315-ecb6-4a90-a8d9-45a46ccec847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tetap']/parent::*</value>
      <webElementGuid>88286e71-7d99-4aa4-8d25-cf508d67ff48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>5053033c-2129-4f83-b7f4-796c9d81439d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-long-value-select-option-1' and (text() = 'Tetap' or . = 'Tetap')]</value>
      <webElementGuid>7d9fc845-66cc-4ba7-a71e-c8c815daa5a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
