<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_dapat_dirundingkan_tidak</name>
   <tag></tag>
   <elementGuidId>9389aa9a-5321-4540-8f98-d2a0549072d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='negotiable2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#negotiable2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d93a083-ff8b-40ce-a69f-1803f0787cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5332eb1b-4e77-4cb3-a738-04c11a877f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>negotiable2</value>
      <webElementGuid>73a87171-cc0c-4de6-a1d6-6e02d1df7106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>negotiable</value>
      <webElementGuid>5bd9094a-b945-4d5b-b17c-41c158039ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>me-2</value>
      <webElementGuid>8ff9f87e-236c-415b-81c5-dae87ef66fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;negotiable2&quot;)</value>
      <webElementGuid>b2bb20e5-d0b1-4577-8183-0362b4695936</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='negotiable2']</value>
      <webElementGuid>d28434b3-addf-4baf-9021-633fac81d600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[3]/div/div/div/div[2]/input</value>
      <webElementGuid>b767b262-791e-49cd-b7ec-a12825d6395e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>105ed496-5f9d-4195-88ae-2e22c4a49e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'negotiable2' and @name = 'negotiable']</value>
      <webElementGuid>160e8d2d-e00e-4e24-9574-3def2fdca82b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
