<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_ketersediaan_segera</name>
   <tag></tag>
   <elementGuidId>60971d32-1113-452b-ad5a-a882ca6524c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ketersediaan1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ketersediaan1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a78a2420-4d1c-4fed-8781-8bc2c722cd0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>me-2</value>
      <webElementGuid>ba3e1dd7-343f-402c-9d06-ec780fd46db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>be254a9a-0195-49e9-90d5-fa70074a3b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ketersediaan</value>
      <webElementGuid>f7b62536-11c1-41fc-9ae2-6c3f732050c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ketersediaan1</value>
      <webElementGuid>a88740fa-3b7f-47d1-8a7e-a9631a8516ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ketersediaan1&quot;)</value>
      <webElementGuid>2e6b7a39-f8e9-406a-bb87-65cb936b2731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ketersediaan1']</value>
      <webElementGuid>e6c0f09b-b111-4e92-9e47-bcc5ce33a796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[4]/div/div/div/div/input</value>
      <webElementGuid>3e588c3b-15b2-42fb-a7aa-6084b1b4f86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>7e99ee22-843e-4d94-a9cf-ee480e1b3171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ketersediaan' and @id = 'ketersediaan1']</value>
      <webElementGuid>4f0331e9-2085-4b37-bfb0-5c7a9cae902f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
