<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radiobtn_dapat_dirundingkan_ya</name>
   <tag></tag>
   <elementGuidId>0c627ffc-ffd6-4366-b905-68b85c13a364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='negotiable1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#negotiable1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42fb9694-ac66-4e01-8f01-b5b2b72ff292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>275177e3-fb58-45d8-9df3-c7e64cbce272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>negotiable1</value>
      <webElementGuid>36279daa-69a3-4f01-b9f9-9d07254e0e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>negotiable</value>
      <webElementGuid>fe446f53-0247-42a2-b5ce-835bb3fa8d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>me-2</value>
      <webElementGuid>4190a5f3-e5ff-4294-9943-384a0c396151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;negotiable1&quot;)</value>
      <webElementGuid>cd73991d-333e-4ffa-ab52-ebb95b82dc5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='negotiable1']</value>
      <webElementGuid>c937260f-af61-4bd5-9fe8-a443173a45fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[3]/div/div/div/div/input</value>
      <webElementGuid>8b24ba84-a546-4e56-ad52-ee404ffd11b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/input</value>
      <webElementGuid>e8ab110c-4a0e-485f-9db6-a765491c1a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'negotiable1' and @name = 'negotiable']</value>
      <webElementGuid>bf7cca0f-2ef4-4a6c-a75f-46d2d7558898</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
