<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Pendidikan FormalPendidikanNama Sekola_2270ac</name>
   <tag></tag>
   <elementGuidId>ffea5417-c482-4f42-98cf-98fa4ed7d6c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/section[3]/form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>56b21203-e759-43f5-9da4-bf4a46837cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>821cb192-e292-4bf7-87cd-6d46246edd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pendidikan FormalPendidikanNama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKSMA *D3 S1 *S2 Pendidikan SMA *Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan D3 Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan S1 *Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan S2 Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan Non-FormalPelatihanNama InstitusiTahun MulaiTahun SelesaiSertifikat--Pilih--YaTidak--Pilih--YaTidakPelatihanNama InstitusiTahun MulaiTahun SelesaiSertifikat--Pilih--YaTidakPelatihanNama InstitusiTahun MulaiTahun SelesaiSertifikat--Pilih--YaTidakTambah PelatihanOrganisasi / Aktivitas Sosial / Kegiatan LainJenis KegiatanOrganisasi / LembagaPeriodeJabatanKeterangan LainJenis KegiatanOrganisasi / LembagaPeriodeJabatanKeterangan LainTambah KegiatanKegiatan pada waktu luang / hobi *</value>
      <webElementGuid>da85fe50-717d-4f9f-a12d-42c780451c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]</value>
      <webElementGuid>ce088035-0457-42d7-ac9c-f6e1ebd948ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form</value>
      <webElementGuid>452626dd-e8ed-4fda-919d-c5a8b1d0f5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Profil'])[1]/following::form[1]</value>
      <webElementGuid>67122815-1ba3-42b5-87c8-6c53cd603034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil'])[1]/following::form[1]</value>
      <webElementGuid>325f4d03-3c83-4629-8180-e4b418e97980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/form</value>
      <webElementGuid>c586b025-c372-4ae0-8465-05365fe569a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = 'Pendidikan FormalPendidikanNama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKSMA *D3 S1 *S2 Pendidikan SMA *Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan D3 Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan S1 *Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan S2 Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan Non-FormalPelatihanNama InstitusiTahun MulaiTahun SelesaiSertifikat--Pilih--YaTidak--Pilih--YaTidakPelatihanNama InstitusiTahun MulaiTahun SelesaiSertifikat--Pilih--YaTidakPelatihanNama InstitusiTahun MulaiTahun SelesaiSertifikat--Pilih--YaTidakTambah PelatihanOrganisasi / Aktivitas Sosial / Kegiatan LainJenis KegiatanOrganisasi / LembagaPeriodeJabatanKeterangan LainJenis KegiatanOrganisasi / LembagaPeriodeJabatanKeterangan LainTambah KegiatanKegiatan pada waktu luang / hobi *' or . = 'Pendidikan FormalPendidikanNama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKSMA *D3 S1 *S2 Pendidikan SMA *Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan D3 Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan S1 *Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan S2 Nama Sekolah / UniversitasTahun MulaiTahun SelesaiJurusanIPKPendidikan Non-FormalPelatihanNama InstitusiTahun MulaiTahun SelesaiSertifikat--Pilih--YaTidak--Pilih--YaTidakPelatihanNama InstitusiTahun MulaiTahun SelesaiSertifikat--Pilih--YaTidakPelatihanNama InstitusiTahun MulaiTahun SelesaiSertifikat--Pilih--YaTidakTambah PelatihanOrganisasi / Aktivitas Sosial / Kegiatan LainJenis KegiatanOrganisasi / LembagaPeriodeJabatanKeterangan LainJenis KegiatanOrganisasi / LembagaPeriodeJabatanKeterangan LainTambah KegiatanKegiatan pada waktu luang / hobi *')]</value>
      <webElementGuid>da24e6f2-28a1-4709-ae06-c6863d62ddc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
