<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keterangan Lain_keterangan0</name>
   <tag></tag>
   <elementGuidId>94a17a3f-1a42-4eb3-afd9-f7079ecc1b0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keterangan0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#keterangan0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>229e4221-e83a-43fb-a696-ba59e9ea006e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55754d50-038a-44d5-990c-a3089d1a4c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3695efe7-d1b7-485e-bb30-7008e33d077b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>302c2102-d329-48b1-926c-92f66913c5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keterangan0</value>
      <webElementGuid>abf105d8-037e-4d28-97a7-45ba6de9c60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;text-black null&quot;]/td[@class=&quot;py-3&quot;]/input[@id=&quot;keterangan0&quot;]</value>
      <webElementGuid>e3f557bb-ad8f-43d3-997b-c23859699a80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keterangan0']</value>
      <webElementGuid>f0f94944-3e63-45cb-bf56-596a3faaec92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[6]/table/tbody/tr/td[5]/input</value>
      <webElementGuid>42fc4e2a-be2b-4e80-8630-83ea15913c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/table/tbody/tr/td[5]/input</value>
      <webElementGuid>b318b506-26a8-42c8-b7bf-dcce646ea277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'keterangan0']</value>
      <webElementGuid>518f94b6-95d3-4cee-a017-aab8a89e9cf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
