<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Pilih--YaTidak_1</name>
   <tag></tag>
   <elementGuidId>42414f73-dd2f-4133-8ea5-0f795eb14dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sertifikat1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sertifikat1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f2c2ccd0-c618-4896-a48b-bcc43c1fef8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>dfee987b-99df-42d5-8b64-033acecd1e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sertifikat1</value>
      <webElementGuid>26d47ffa-7184-4700-8041-e9c7ca73213c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Pilih--YaTidak</value>
      <webElementGuid>c84e3fb5-6a7f-4940-9eef-f84b5a1cd4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;text-black null&quot;]/td[@class=&quot;py-3&quot;]/select[@id=&quot;sertifikat1&quot;]</value>
      <webElementGuid>0d3c52f3-e22d-45c9-808e-b0e43ecc2a39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sertifikat1']</value>
      <webElementGuid>8a25dbeb-2fca-4656-9d80-024a5e9107f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[3]/table/tbody/tr[2]/td[5]/select</value>
      <webElementGuid>e20bed9c-6d7e-4ac0-94fb-ca522afe64ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikat'])[1]/following::select[2]</value>
      <webElementGuid>f7da9fb9-6435-4273-aa9c-0b2e6d32e493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Selesai'])[6]/following::select[2]</value>
      <webElementGuid>5ab33e9f-0417-4a5a-a5ae-cb22e726032f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelatihan'])[2]/preceding::select[1]</value>
      <webElementGuid>d48e58f2-001b-4753-a4f3-9eb252bb97dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Institusi'])[2]/preceding::select[1]</value>
      <webElementGuid>1ce050c1-43f6-4034-a6f4-b2a37732b373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[5]/select</value>
      <webElementGuid>76096a9c-ce42-4e87-ae80-4fd9b2768897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sertifikat1' and (text() = '--Pilih--YaTidak' or . = '--Pilih--YaTidak')]</value>
      <webElementGuid>a27d765c-7383-4734-8236-04d549468f13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
