<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Belajar hal baru, membaca berita, dan_1</name>
   <tag></tag>
   <elementGuidId>43125915-5810-412c-bd4d-3a7ffb47c806</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='hobi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hobi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>26a34eb6-cbbc-49c0-b241-a5c9cbb43423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>991f09cd-df41-4298-a3ac-554b84036a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-4 undefined</value>
      <webElementGuid>ce3b2524-b5fd-46c1-ab3c-ef26364c1b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobi</value>
      <webElementGuid>3109a0dc-e082-4237-8221-f76782584dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>f247d332-a30f-4294-bb76-9f1e4777eb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belajar hal baru, membaca berita, dan </value>
      <webElementGuid>30acc771-1b24-4cc1-b59d-ee022e5ecc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobi&quot;)</value>
      <webElementGuid>68d224e1-a90e-41df-b13c-7e3f23a3eac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='hobi']</value>
      <webElementGuid>df6ae28a-b7ca-401a-aa65-ab9330ec2f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[9]/div/textarea</value>
      <webElementGuid>c4d4bdea-8103-401f-9a94-e366bbb05264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::textarea[1]</value>
      <webElementGuid>4376fff3-6120-48cb-b486-dd1edee9c362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::textarea[1]</value>
      <webElementGuid>ac1dcdc6-de77-49c5-ba55-415485952308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/preceding::textarea[1]</value>
      <webElementGuid>e90a1e7c-8f44-4cfd-99e0-ab800319cfba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Belajar hal baru, membaca berita, dan']/parent::*</value>
      <webElementGuid>1184fd01-123b-4c6b-8de8-b1241993d4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>ce38b08e-3fd8-48a8-b099-3efb0824ebec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'hobi' and (text() = 'Belajar hal baru, membaca berita, dan ' or . = 'Belajar hal baru, membaca berita, dan ')]</value>
      <webElementGuid>af09a763-d492-4222-b24b-3509c51cb60d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
