<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Belajar hal baru, membaca berita, _c6b860</name>
   <tag></tag>
   <elementGuidId>45aef711-1664-4796-a484-3ef78ca6a0c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='hobi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hobi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>130773f3-e3b6-4864-9e23-1847580e1125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>31c4bdd8-239a-4726-a4e8-380185bf1280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-4 undefined</value>
      <webElementGuid>f338042a-f546-4378-8bdf-76d802b51ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobi</value>
      <webElementGuid>954d722b-a4d1-46c7-85ff-73fb61ee08a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>6e38508c-5fa6-416b-baae-d46d4bd43076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belajar hal baru, membaca berita, dan membaca pikir</value>
      <webElementGuid>339b6a9d-8e9a-4e83-be88-2f7cee89f42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobi&quot;)</value>
      <webElementGuid>f32fb2fd-8961-4f59-aaec-145a64ecca15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='hobi']</value>
      <webElementGuid>8f5bf134-0cab-4e31-8ead-cc253207a88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[9]/div/textarea</value>
      <webElementGuid>f883a7d7-db05-45e5-af30-f275f95b4409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::textarea[1]</value>
      <webElementGuid>7ccbcbeb-0cda-4a1d-89c7-8ce811fc509d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::textarea[1]</value>
      <webElementGuid>df36daf4-1c2f-46ed-8a7a-7659f5c43c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/preceding::textarea[1]</value>
      <webElementGuid>ce293a52-7b3f-4d99-80d7-17168c6bcecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Belajar hal baru, membaca berita, dan membaca pikir']/parent::*</value>
      <webElementGuid>c7e883ce-297b-426c-9714-4cafd5de657b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cf26ef0e-bff0-4dc7-bcaa-dd059bb5fd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'hobi' and (text() = 'Belajar hal baru, membaca berita, dan membaca pikir' or . = 'Belajar hal baru, membaca berita, dan membaca pikir')]</value>
      <webElementGuid>394e0dbb-98f7-4149-9fe3-a533f835f6e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
