<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Belajar hal baru, membaca berita, _ede11b</name>
   <tag></tag>
   <elementGuidId>1077f953-f861-401a-bb40-57cf1451cdc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='hobi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hobi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8ac7f93a-b548-412c-ade9-7cd0d486e58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>88336db7-2fb0-45e1-bf13-2009224d031b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mb-4 undefined</value>
      <webElementGuid>ee33b5a0-b014-44bc-8e71-9602ad51698f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hobi</value>
      <webElementGuid>9dd423e3-81d6-4959-b8f6-320d1279a302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>71ceab9d-20ab-405f-bc59-47829fdcce48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Belajar hal baru, membaca berita, dan membaca pikira</value>
      <webElementGuid>c5577006-a1f2-4cfe-8272-d5d604a40c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hobi&quot;)</value>
      <webElementGuid>12f03786-41b3-4420-a887-249d36004637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='hobi']</value>
      <webElementGuid>5932972f-3f7a-4fc1-8a90-804146708379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[9]/div/textarea</value>
      <webElementGuid>742ca51f-81bb-4fd6-962c-a07aa608d497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::textarea[1]</value>
      <webElementGuid>8ae7044b-b023-47d4-bd30-d937a0db0649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::textarea[1]</value>
      <webElementGuid>8937788c-1e2f-4838-b017-aeafe078c620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[1]/preceding::textarea[1]</value>
      <webElementGuid>f185aca7-dad5-4b16-9d1e-913904d83604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Belajar hal baru, membaca berita, dan membaca pikira']/parent::*</value>
      <webElementGuid>4d7eadda-32cc-4760-b9c5-32776afb32bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e8af8858-4179-41fa-a529-5d8869a4e050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'hobi' and (text() = 'Belajar hal baru, membaca berita, dan membaca pikira' or . = 'Belajar hal baru, membaca berita, dan membaca pikira')]</value>
      <webElementGuid>63a17811-677f-4679-b96f-af55e3151ef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
