<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_dropdown_pelatihan_sertifikat1</name>
   <tag></tag>
   <elementGuidId>c062466e-bfcd-447f-8898-f62df239505d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sertifikat0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sertifikat0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ca6a1c96-cee8-4083-9945-3835fe947ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select</value>
      <webElementGuid>8a612801-089f-472d-8036-b36797d8ddfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sertifikat0</value>
      <webElementGuid>7220088f-4d91-4c18-9381-ecffa46e3a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Pilih--YaTidak</value>
      <webElementGuid>3e73b252-d05b-4c32-b7b2-2b27fcd65458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;edit-profile container&quot;]/section[@class=&quot;form-section2&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;mobile-dis-none&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[@class=&quot;text-black null&quot;]/td[@class=&quot;py-3&quot;]/select[@id=&quot;sertifikat0&quot;]</value>
      <webElementGuid>f67e9c37-f21b-4804-9ecc-6aace94dd6ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sertifikat0']</value>
      <webElementGuid>d10898c2-68ce-450b-8eef-3b3fa2cb278a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/section[3]/form/div[3]/table/tbody/tr/td[5]/select</value>
      <webElementGuid>13462668-2be7-47cd-9540-b9ae3ca7cbad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sertifikat'])[1]/following::select[1]</value>
      <webElementGuid>e39edbc2-91a5-47c5-afee-dbbde10d5f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tahun Selesai'])[6]/following::select[1]</value>
      <webElementGuid>3a349bea-2d6f-4126-9a77-fce2d4be9570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pelatihan'])[2]/preceding::select[1]</value>
      <webElementGuid>31a8a293-027f-44ad-ae5b-2a575b0ee1aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Institusi'])[2]/preceding::select[1]</value>
      <webElementGuid>75ac9a92-f3cf-432a-83b0-0f87b9294b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>dd510a25-c1e8-4180-9c74-28c875525b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sertifikat0' and (text() = '--Pilih--YaTidak' or . = '--Pilih--YaTidak')]</value>
      <webElementGuid>1ebe4c59-4d1c-4465-a7da-42f8642e16c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
